# Generated by Django 4.2.4 on 2023-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
